### ISSUE TITLE
[Bug] Double Validation des demandes : duplicate key value violates unique constraint "application_pkey"

### ISSUE THREAD

**Issue by jdauphant** [betagouv/aplus#802]
"UnexpectedException: Unexpected exception[PSQLException: ERROR: duplicate key value violates unique constraint "application_pkey"
  Detail: Key (id)=(9f953077-154d-4c6a-8d67-0f7d709c1228) already exists.]
    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:355)
    at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:261)
    at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:429)
    at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:421)
    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:453)
...
(11 additional frame(s) were not displayed)

PSQLException: ERROR: duplicate key value violates unique constraint "application_pkey"
  Detail: Key (id)=(9f953077-154d-4c6a-8d67-0f7d709c1228) already exists.
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
...
(39 additional frame(s) were not displayed)"

**Comment by niladic** [comment]
🔨 id à supprimer du formulaire de la demande
